services:
  lifearcade:
    build: .
    ports:
      - "80:4173"
    restart: unless-stopped
    container_name: lifearcade-kiosk

    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
